DROP TABLE ORDERS CASCADE CONSTRAINTS;
DROP TABLE CUSTOMER CASCADE CONSTRAINTS;
DROP TABLE RESTAURANT CASCADE CONSTRAINTS;
DROP TABLE EMPLOYEES CASCADE CONSTRAINTS;
DROP SEQUENCE seqOID;
DROP SEQUENCE seqCID;
DROP SEQUENCE seqRID;
DROP SEQUENCE seqEID;
CREATE TABLE EMPLOYEES(
  Lname  Char(50)  NOT NULL,
  Fname  Char(50)  NOT NULL,
  PhoneNum  Char(12)  NOT NULL,
  HoursWorked  Int  NOT NULL,
  EmployeeID  Int  NOT NULL,
  CONSTRAINT  EMPLOYEES_PK  PRIMARY KEY(EmployeeID)
  );
CREATE SEQUENCE seqEID INCREMENT BY 1 START WITH 1;
CREATE TABLE CUSTOMER(
  Lname  Char(50)  NOT NULL,
  Fname  Char(50)  NOT NULL,
  PhoneNum  Char(12)  NOT NULL,
  CustomerID  Int  NOT NULL,
  CONSTRAINT  Customer_PK  PRIMARY KEY(CustomerID)
  );
