DROP TABLE ORDERS CASCADE CONSTRAINTS;
DROP TABLE CUSTOMER CASCADE CONSTRAINTS;
DROP TABLE RESTAURANT CASCADE CONSTRAINTS;
DROP TABLE EMPLOYEES CASCADE CONSTRAINTS;
DROP SEQUENCE seqOID;
DROP SEQUENCE seqCID;
DROP SEQUENCE seqRID;
DROP SEQUENCE seqEID;
